//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T состояние.
    /// </summary>
    // *** Start programmer edit section *** (tСостояние CustomAttributes)

    // *** End programmer edit section *** (tСостояние CustomAttributes)
    public enum tСостояние
    {
        
        // *** Start programmer edit section *** (tСостояние.Новый CustomAttributes)

        // *** End programmer edit section *** (tСостояние.Новый CustomAttributes)
        Новый,
        
        // *** Start programmer edit section *** (tСостояние.НеобходимРемонт CustomAttributes)

        // *** End programmer edit section *** (tСостояние.НеобходимРемонт CustomAttributes)
        НеобходимРемонт,
    }
}
